test_1_user_registration: Faker 1
test_2_user_login: Yaml

# test1_user_registration: use_file=False
#                          amount_faker=2


# Убрать создание файлов
#Датафейкер дженерал для всех
# иЗМЕНИТЬ ЭТОТ КОНФИГ ФАЙЛ
